#!/usr/bin/env python3

# Main script for Adafruit Internet of Things Printer 2.  Monitors button
# for taps and holds, performs periodic actions (Twitter polling by default)
# and daily actions (Sudoku and weather by default).
#
# Written by Adafruit Industries.  MIT license.
#
# MUST BE RUN AS ROOT (due to GPIO access)
#
# Required software includes Adafruit_Thermal, Python Imaging, and PySerial
# libraries. Other libraries used are part of stock Python install.
#
# Resources:
# http://www.adafruit.com/products/597 Mini Thermal Receipt Printer
# http://www.adafruit.com/products/600 Printer starter pack

import RPi.GPIO as GPIO
import socket
import subprocess
import time

import .twitter_statuses

import argparse
import sys

parser = argparse.ArgumentParser(description="Run the IOT printer.")
parser.add_argument(
    "-c", "--config-file", required=True, help="The configuration `.ini` file."
)
parser.add_argument(
    "--last-id", default=0, type=int, help="The ID of the last tweet printed."
)
parser.add_argument(
    "-v", "--verbose", action="store_true", help="Enable verbose DEBUG logging."
)
args = parser.parse_args()

log_level = logging.INFO
if args.verbose:
    log_level = logging.DEBUG

logging.basicConfig(format="[%(levelname)s]\t(%(name)s)\t%(message)s", level=log_level)

log = logging.getLogger(__name__)

# Processor load is heavy at startup; wait a moment to avoid
# stalling during greeting.
# XXX time.sleep(30)

sys.exit(0)

